<a href="https://colab.research.google.com/github/sunny7016/Aiml/blob/main/aiml_07082024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np
a = np.array([1,2,3,4])
b =np.array([2,7,8,10])
c=a+b
print(c)
c.sort()
d = np.array([(2,5,6),(55,78,23)])
e = np.array([(45,7,89),(45,67,23)])
f=d+e
print(f)
g= np.zeros((3,3))
g
i=np.arange(10,55,6)
i
j=np.linspace(2,6,7)
j
k=np.full((2,2),7)
k
n= np.random.random((2,2))
n


[ 3  9 11 14]
[[ 47  12  95]
 [100 145  46]]


array([[0.10083606, 0.92195562],
       [0.18950855, 0.77620715]])